name: Test - Terraform test action
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
    paths:

      - 'src/*'
      - 'action.yml'
      - '.github/workflows/test.yml'

jobs:
  aws_test:
    name: Test - terraform test action
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - id: aws_test
        name: Test - AWS
        uses: ./
        with:
          ROOT_DIR: '${{ github.workspace }}/tests/aws'

      - id: aws_test
        name: Test - AWS
        uses: ./
        with:
          ROOT_DIR: '${{ github.workspace }}/tests/azure'
       

  
          
